require "test_helper"

class DaySixTest < Minitest::Test
  def test_aoc_part_one
    room = %w[
      ....#.....
      .........#
      ..........
      ..#.......
      .......#..
      ..........
      .#..^.....
      ........#.
      #.........
      ......#...
    ]

    result = Aoc2024::Guard.new.patrol room

    assert_equal(41, result.sum { |row| row.count "X" })
  end
end
